### Create a report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "mercedes-benz",
    "model": "c class",
    "year": 1984,
    "mileage": 208000,
    "lng": 32,
    "lat": 32,
    "price": 15500
}

### Approve an existing report
PATCH http://localhost:3000/reports/7
content-type: application/json

{
    "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=mercedes-benz&model=c%20class&lng=35&lat=35&mileage=50000&year=1982&price=15000